# 服务器配置
server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anti_fraud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root  # 你的MySQL用户名
    password: 123456  # 你的MySQL密码

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.entity

